import hashlib
import json
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]


def test_product_api_contract_is_reproducible_and_covers_every_stable_route():
    contract_path = ROOT / "sdk" / "product-api-contract.json"
    contract = json.loads(contract_path.read_text())
    parity = json.loads((ROOT / "internal" / "api" / "mcp_route_parity_registry.json").read_text())
    assert contract["authority"] == "PRODUCT_API_CONTRACT_AUTHORITY_V1"
    assert contract["source"] == "internal/api/server.go"
    assert contract["routeCount"] == parity["routeCount"] == len(contract["routes"])
    assert {(r["method"], r["path"]) for r in contract["routes"]} == {(r["method"], r["path"]) for r in parity["routes"]}
    canonical = json.dumps(contract["routes"], separators=(",", ":"), sort_keys=True).encode()
    assert contract["routeDigest"] == "sha256:" + hashlib.sha256(canonical).hexdigest()
    subprocess.run(["python3", "scripts/generate_product_api_contract.py", "--check", "."], cwd=ROOT, check=True)


def test_generated_go_route_catalog_is_not_hand_maintained():
    generated = (ROOT / "sdk" / "go" / "routes_gen.go").read_text()
    assert "Code generated by scripts/generate_product_api_contract.py; DO NOT EDIT." in generated
    assert "ProductAPIContractAuthority = \"PRODUCT_API_CONTRACT_AUTHORITY_V1\"" in generated
