package api

import (
	"context"
	"net/http"
	"strings"

	"platform.4so.io/factory/internal/controlplane"
)

type applicationPlatformStore interface {
	CreateWorkloadType(context.Context,controlplane.WorkloadType,string)(controlplane.WorkloadType,error)
	GetWorkloadType(context.Context,string)(controlplane.WorkloadType,error)
	ListWorkloadTypes(context.Context,string)([]controlplane.WorkloadType,error)
	CreateCapabilityTrait(context.Context,controlplane.CapabilityTrait,string)(controlplane.CapabilityTrait,error)
	GetCapabilityTrait(context.Context,string)(controlplane.CapabilityTrait,error)
	ListCapabilityTraits(context.Context,string)([]controlplane.CapabilityTrait,error)
	CreateManagedResourceType(context.Context,controlplane.ManagedResourceType,string)(controlplane.ManagedResourceType,error)
	GetManagedResourceType(context.Context,string)(controlplane.ManagedResourceType,error)
	ListManagedResourceTypes(context.Context,string)([]controlplane.ManagedResourceType,error)
	CreateWorkspaceProfile(context.Context,controlplane.WorkspaceProfile,string)(controlplane.WorkspaceProfile,error)
	GetWorkspaceProfile(context.Context,string)(controlplane.WorkspaceProfile,error)
	ListWorkspaceProfiles(context.Context,string)([]controlplane.WorkspaceProfile,error)
	CreateApplicationRelease(context.Context,controlplane.ApplicationReleaseCreateRequest,string)(controlplane.ApplicationRelease,error)
	GetApplicationRelease(context.Context,string)(controlplane.ApplicationRelease,error)
	ListApplicationReleases(context.Context,string)([]controlplane.ApplicationRelease,error)
	CreateEnvironmentBinding(context.Context,controlplane.EnvironmentBindingCreateRequest,string)(controlplane.EnvironmentBinding,error)
	PromoteEnvironmentBinding(context.Context,string,int64,controlplane.EnvironmentBindingPromotionRequest,string)(controlplane.EnvironmentBinding,error)
	GetEnvironmentBinding(context.Context,string)(controlplane.EnvironmentBinding,error)
	ListEnvironmentBindings(context.Context,string)([]controlplane.EnvironmentBinding,error)
}

func(s *Server)applicationPlatformAuthority(w http.ResponseWriter)(applicationPlatformStore,bool){v,ok:=s.store.(applicationPlatformStore);if !ok{writeError(w,http.StatusServiceUnavailable,"APPLICATION_PLATFORM_AUTHORITY_UNAVAILABLE","application platform persistence authority is unavailable")};return v,ok}
func(s *Server)applicationProjectWrite(w http.ResponseWriter,r *http.Request,projectID string)(string,bool){actor,err:=actorID(r);if err!=nil{writeError(w,http.StatusUnauthorized,"ACTOR_REQUIRED",err.Error());return "",false};if _,err=s.requireProjectAccess(r,strings.TrimSpace(projectID),organizationWrite);err!=nil{writeScopeError(w,err);return "",false};return actor,true}
func(s *Server)applicationProjectRead(w http.ResponseWriter,r *http.Request,projectID string)bool{if _,err:=s.requireProjectAccess(r,strings.TrimSpace(projectID),organizationRead);err!=nil{writeScopeError(w,err);return false};return true}

func(s *Server)createWorkloadType(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};var in controlplane.WorkloadType;if err:=decodeJSON(w,r,&in);err!=nil{writeError(w,400,"INVALID_REQUEST",err.Error());return};actor,ok:=s.applicationProjectWrite(w,r,in.ProjectID);if !ok{return};v,err:=st.CreateWorkloadType(r.Context(),in,actor);if err!=nil{writeStoreError(w,err);return};writeJSON(w,201,v)}
func(s *Server)getWorkloadType(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};v,err:=st.GetWorkloadType(r.Context(),r.PathValue("id"));if err!=nil{writeStoreError(w,err);return};if !s.applicationProjectRead(w,r,v.ProjectID){return};writeJSON(w,200,v)}
func(s *Server)listWorkloadTypes(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};pid:=strings.TrimSpace(r.URL.Query().Get("projectId"));if pid!=""&&!s.applicationProjectRead(w,r,pid){return};v,err:=st.ListWorkloadTypes(r.Context(),pid);if err!=nil{writeStoreError(w,err);return};allowed,all,err:=s.accessibleProjectSet(r);if err!=nil{writeStoreError(w,err);return};v=filterProjectScoped(v,allowed,all,func(x controlplane.WorkloadType)string{return x.ProjectID});writeJSON(w,200,v)}

func(s *Server)createCapabilityTrait(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};var in controlplane.CapabilityTrait;if err:=decodeJSON(w,r,&in);err!=nil{writeError(w,400,"INVALID_REQUEST",err.Error());return};actor,ok:=s.applicationProjectWrite(w,r,in.ProjectID);if !ok{return};v,err:=st.CreateCapabilityTrait(r.Context(),in,actor);if err!=nil{writeStoreError(w,err);return};writeJSON(w,201,v)}
func(s *Server)getCapabilityTrait(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};v,err:=st.GetCapabilityTrait(r.Context(),r.PathValue("id"));if err!=nil{writeStoreError(w,err);return};if !s.applicationProjectRead(w,r,v.ProjectID){return};writeJSON(w,200,v)}
func(s *Server)listCapabilityTraits(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};pid:=strings.TrimSpace(r.URL.Query().Get("projectId"));if pid!=""&&!s.applicationProjectRead(w,r,pid){return};v,err:=st.ListCapabilityTraits(r.Context(),pid);if err!=nil{writeStoreError(w,err);return};allowed,all,err:=s.accessibleProjectSet(r);if err!=nil{writeStoreError(w,err);return};v=filterProjectScoped(v,allowed,all,func(x controlplane.CapabilityTrait)string{return x.ProjectID});writeJSON(w,200,v)}

func(s *Server)createManagedResourceType(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};var in controlplane.ManagedResourceType;if err:=decodeJSON(w,r,&in);err!=nil{writeError(w,400,"INVALID_REQUEST",err.Error());return};actor,ok:=s.applicationProjectWrite(w,r,in.ProjectID);if !ok{return};v,err:=st.CreateManagedResourceType(r.Context(),in,actor);if err!=nil{writeStoreError(w,err);return};writeJSON(w,201,v)}
func(s *Server)getManagedResourceType(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};v,err:=st.GetManagedResourceType(r.Context(),r.PathValue("id"));if err!=nil{writeStoreError(w,err);return};if !s.applicationProjectRead(w,r,v.ProjectID){return};writeJSON(w,200,v)}
func(s *Server)listManagedResourceTypes(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};pid:=strings.TrimSpace(r.URL.Query().Get("projectId"));if pid!=""&&!s.applicationProjectRead(w,r,pid){return};v,err:=st.ListManagedResourceTypes(r.Context(),pid);if err!=nil{writeStoreError(w,err);return};allowed,all,err:=s.accessibleProjectSet(r);if err!=nil{writeStoreError(w,err);return};v=filterProjectScoped(v,allowed,all,func(x controlplane.ManagedResourceType)string{return x.ProjectID});writeJSON(w,200,v)}

func(s *Server)createWorkspaceProfile(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};var in controlplane.WorkspaceProfile;if err:=decodeJSON(w,r,&in);err!=nil{writeError(w,400,"INVALID_REQUEST",err.Error());return};actor,ok:=s.applicationProjectWrite(w,r,in.ProjectID);if !ok{return};v,err:=st.CreateWorkspaceProfile(r.Context(),in,actor);if err!=nil{writeStoreError(w,err);return};writeJSON(w,201,v)}
func(s *Server)getWorkspaceProfile(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};v,err:=st.GetWorkspaceProfile(r.Context(),r.PathValue("id"));if err!=nil{writeStoreError(w,err);return};if !s.applicationProjectRead(w,r,v.ProjectID){return};writeJSON(w,200,v)}
func(s *Server)listWorkspaceProfiles(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};pid:=strings.TrimSpace(r.URL.Query().Get("projectId"));if pid!=""&&!s.applicationProjectRead(w,r,pid){return};v,err:=st.ListWorkspaceProfiles(r.Context(),pid);if err!=nil{writeStoreError(w,err);return};allowed,all,err:=s.accessibleProjectSet(r);if err!=nil{writeStoreError(w,err);return};v=filterProjectScoped(v,allowed,all,func(x controlplane.WorkspaceProfile)string{return x.ProjectID});writeJSON(w,200,v)}

type applicationResolveInput struct{ProjectID string `json:"projectId"`;WorkloadTypeID string `json:"workloadTypeId"`;TraitIDs []string `json:"traitIds"`;ObservedNativeCapabilities []string `json:"observedNativeCapabilities"`}
func(s *Server)resolveApplicationPlatformComposition(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};var in applicationResolveInput;if err:=decodeJSON(w,r,&in);err!=nil{writeError(w,400,"INVALID_REQUEST",err.Error());return};if !s.applicationProjectRead(w,r,in.ProjectID){return};wt,err:=st.GetWorkloadType(r.Context(),in.WorkloadTypeID);if err!=nil||wt.ProjectID!=strings.TrimSpace(in.ProjectID){if err==nil{err=controlplane.ErrNotFound};writeStoreError(w,err);return};traits:=[]controlplane.CapabilityTrait{};for _,id:=range in.TraitIDs{v,e:=st.GetCapabilityTrait(r.Context(),id);if e!=nil||v.ProjectID!=wt.ProjectID{if e==nil{e=controlplane.ErrNotFound};writeStoreError(w,e);return};traits=append(traits,v)};out,err:=controlplane.ResolveWorkloadComposition(wt,traits,in.ObservedNativeCapabilities);if err!=nil{writeStoreError(w,err);return};writeJSON(w,200,out)}

func(s *Server)createApplicationRelease(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};var in controlplane.ApplicationReleaseCreateRequest;if err:=decodeJSON(w,r,&in);err!=nil{writeError(w,400,"INVALID_REQUEST",err.Error());return};actor,ok:=s.applicationProjectWrite(w,r,in.ProjectID);if !ok{return};v,err:=st.CreateApplicationRelease(r.Context(),in,actor);if err!=nil{writeStoreError(w,err);return};writeJSON(w,201,v)}
func(s *Server)getApplicationRelease(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};v,err:=st.GetApplicationRelease(r.Context(),r.PathValue("id"));if err!=nil{writeStoreError(w,err);return};if !s.applicationProjectRead(w,r,v.ProjectID){return};writeJSON(w,200,v)}
func(s *Server)listApplicationReleases(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};pid:=strings.TrimSpace(r.URL.Query().Get("projectId"));if pid!=""&&!s.applicationProjectRead(w,r,pid){return};v,err:=st.ListApplicationReleases(r.Context(),pid);if err!=nil{writeStoreError(w,err);return};allowed,all,err:=s.accessibleProjectSet(r);if err!=nil{writeStoreError(w,err);return};v=filterProjectScoped(v,allowed,all,func(x controlplane.ApplicationRelease)string{return x.ProjectID});writeJSON(w,200,v)}

func(s *Server)createEnvironmentBinding(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};var in controlplane.EnvironmentBindingCreateRequest;if err:=decodeJSON(w,r,&in);err!=nil{writeError(w,400,"INVALID_REQUEST",err.Error());return};release,err:=st.GetApplicationRelease(r.Context(),in.ReleaseID);if err!=nil{writeStoreError(w,err);return};actor,ok:=s.applicationProjectWrite(w,r,release.ProjectID);if !ok{return};v,err:=st.CreateEnvironmentBinding(r.Context(),in,actor);if err!=nil{writeStoreError(w,err);return};writeJSON(w,201,v)}
func(s *Server)getEnvironmentBinding(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};v,err:=st.GetEnvironmentBinding(r.Context(),r.PathValue("id"));if err!=nil{writeStoreError(w,err);return};if !s.applicationProjectRead(w,r,v.ProjectID){return};writeJSON(w,200,v)}
func(s *Server)listEnvironmentBindings(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};pid:=strings.TrimSpace(r.URL.Query().Get("projectId"));if pid!=""&&!s.applicationProjectRead(w,r,pid){return};v,err:=st.ListEnvironmentBindings(r.Context(),pid);if err!=nil{writeStoreError(w,err);return};allowed,all,err:=s.accessibleProjectSet(r);if err!=nil{writeStoreError(w,err);return};v=filterProjectScoped(v,allowed,all,func(x controlplane.EnvironmentBinding)string{return x.ProjectID});writeJSON(w,200,v)}
func(s *Server)promoteEnvironmentBinding(w http.ResponseWriter,r *http.Request){st,ok:=s.applicationPlatformAuthority(w);if !ok{return};current,err:=st.GetEnvironmentBinding(r.Context(),r.PathValue("id"));if err!=nil{writeStoreError(w,err);return};actor,ok:=s.applicationProjectWrite(w,r,current.ProjectID);if !ok{return};expected,err:=parseExpectedRevision(r);if err!=nil{writeError(w,http.StatusPreconditionRequired,"EXPECTED_REVISION_REQUIRED",err.Error());return};var in controlplane.EnvironmentBindingPromotionRequest;if err=decodeJSON(w,r,&in);err!=nil{writeError(w,400,"INVALID_REQUEST",err.Error());return};v,err:=st.PromoteEnvironmentBinding(r.Context(),current.ID,expected,in,actor);if err!=nil{writeStoreError(w,err);return};setRevisionETag(w,v.Revision);writeJSON(w,200,v)}
