FROM scratch

ARG SOURCE_RELEASE_DIGEST
ARG VIRTUAL_CLUSTER_ACQUISITION_DIGEST

LABEL platform.4so.io/product-role="virtual-cluster-runtime" \
      platform.4so.io/source-release-digest="${SOURCE_RELEASE_DIGEST}" \
      platform.4so.io/virtual-cluster-acquisition-digest="${VIRTUAL_CLUSTER_ACQUISITION_DIGEST}"

COPY --chmod=0555 helm /usr/local/bin/helm
COPY --chmod=0555 virtual-cluster-renderer /usr/local/bin/4so-vcluster-post-renderer
COPY --chmod=0444 vcluster.tgz /runtime/vcluster.tgz
COPY --chmod=0444 execution-values.yaml /runtime/execution-values.yaml

USER 65532:65532
ENTRYPOINT ["/usr/local/bin/helm"]
