FROM scratch

ARG SOURCE_RELEASE_DIGEST
ARG DAPR_ACQUISITION_DIGEST

LABEL platform.4so.io/product-role="dapr-runtime" \
      platform.4so.io/source-release-digest="${SOURCE_RELEASE_DIGEST}" \
      platform.4so.io/dapr-acquisition-digest="${DAPR_ACQUISITION_DIGEST}"

COPY --chmod=0555 helm /usr/local/bin/helm
COPY --chmod=0555 dapr-runtime /usr/local/bin/dapr-runtime
COPY --chmod=0444 dapr-1.18.4.tgz /runtime/dapr-1.18.4.tgz

ENV HOME=/home/nonroot
USER 65532:65532
ENTRYPOINT ["/usr/local/bin/dapr-runtime"]
