ARG AWS_CLI_IMAGE
FROM ${AWS_CLI_IMAGE} AS awscli

ARG POSTGRES_RUNTIME_IMAGE
FROM ${POSTGRES_RUNTIME_IMAGE}

# Compose the maintenance toolset from exact pre-acquired image authorities.
# No package manager or network fetch is permitted in this build.
COPY --from=awscli /usr/local/aws-cli/ /usr/local/aws-cli/
COPY --from=awscli /usr/local/bin/aws /usr/local/bin/aws

USER 65532:65532
ENTRYPOINT ["/bin/sh"]
