#!/usr/bin/env python3
"""Generate the stable Product API route contract and dependency-light Go route catalog.

This is deliberately route-bound rather than a handwritten richer SDK: the
server's registered /api/v1 routes remain canonical. Business behavior, RBAC,
approval, durable operations and retries remain server authorities.
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

AUTHORITY = "PRODUCT_API_CONTRACT_AUTHORITY_V1"
SOURCE = "internal/api/server.go"
ROUTE_RE = re.compile(r's\.mux\.HandleFunc\("(GET|POST|PUT|DELETE|PATCH) (/api/v1/[^\"]+)')
PARAM_RE = re.compile(r"\{([^}]+)\}")


def parse_args(argv: list[str]) -> tuple[Path, bool]:
    check = False
    rest: list[str] = []
    for arg in argv:
        if arg == "--check":
            check = True
        else:
            rest.append(arg)
    if len(rest) > 1:
        raise SystemExit("usage: generate_product_api_contract.py [--check] [root]")
    return Path(rest[0] if rest else ".").resolve(), check


def route_rows(root: Path) -> list[dict]:
    server = (root / SOURCE).read_text()
    rows = []
    seen = set()
    for method, path in ROUTE_RE.findall(server):
        key = (method, path)
        if key in seen:
            raise SystemExit(f"duplicate Product API route: {method} {path}")
        seen.add(key)
        family = path[len("/api/v1/"):].split("/")[0]
        rows.append({
            "family": family,
            "method": method,
            "mutation": method != "GET",
            "path": path,
            "pathParams": PARAM_RE.findall(path),
        })
    return rows


def canonical_digest(rows: list[dict]) -> str:
    raw = json.dumps(rows, separators=(",", ":"), sort_keys=True).encode()
    return "sha256:" + hashlib.sha256(raw).hexdigest()


def render_json(root: Path, rows: list[dict]) -> str:
    version = (root / "VERSION").read_text().strip()
    out = {
        "authority": AUTHORITY,
        "generated": True,
        "policy": {
            "approvalBypassAllowed": False,
            "automaticMutationRetryAllowed": False,
            "businessLogicInGeneratedClientAllowed": False,
            "durableOperationAuthorityRemainsServerSide": True,
            "rawCredentialEmbeddingAllowed": False,
        },
        "routeCount": len(rows),
        "routeDigest": canonical_digest(rows),
        "routes": rows,
        "source": SOURCE,
        "version": version,
    }
    return json.dumps(out, indent=2, sort_keys=True) + "\n"


def go_string(value: str) -> str:
    return json.dumps(value)


def render_go(rows: list[dict], digest: str) -> str:
    lines = [
        "// Code generated by scripts/generate_product_api_contract.py; DO NOT EDIT.",
        "package factorysdk",
        "",
        f'const ProductAPIContractAuthority = {go_string(AUTHORITY)}',
        f'const ProductAPIContractDigest = {go_string(digest)}',
        f"const ProductAPIRouteCount = {len(rows)}",
        "",
        "var Routes = []Route{",
    ]
    for row in rows:
        params = "nil"
        if row["pathParams"]:
            params = "[]string{" + ", ".join(go_string(x) for x in row["pathParams"]) + "}"
        lines.append(
            "\t{Method: " + go_string(row["method"]) +
            ", Path: " + go_string(row["path"]) +
            ", Family: " + go_string(row["family"]) +
            ", PathParams: " + params +
            ", Mutation: " + ("true" if row["mutation"] else "false") + "},"
        )
    lines += ["}", ""]
    return "\n".join(lines)


def write_or_check(path: Path, expected: str, check: bool) -> None:
    if check:
        if not path.exists() or path.read_text() != expected:
            raise SystemExit(f"generated Product API contract drift: {path.relative_to(path.parents[1]) if len(path.parents) > 1 else path}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(expected)


def main() -> int:
    root, check = parse_args(sys.argv[1:])
    rows = route_rows(root)
    digest = canonical_digest(rows)
    write_or_check(root / "sdk" / "product-api-contract.json", render_json(root, rows), check)
    write_or_check(root / "sdk" / "go" / "routes_gen.go", render_go(rows, digest), check)
    print(json.dumps({"authority": AUTHORITY, "routeCount": len(rows), "routeDigest": digest, "check": check}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
